[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#FE1B04"  # Linalysis red color
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF0EE"  # Light red background
textColor = "#262626"
font = "sans serif"
