
[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#FE1B04"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
